# Generated by Django 6.1.1 on 2026-09-26 16:31

import apps.accounts.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "login_code",
                    models.CharField(
                        help_text="Short code the employee types to sign in. Assigned by the owner.",
                        max_length=12,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Login code must be 2-12 characters, uppercase letters and digits only.",
                                regex="^[A-Z0-9]{2,12}$",
                            )
                        ],
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Shown in the app and on the owner's review screens.",
                        max_length=80,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("OWNER", "Owner"), ("EMPLOYEE", "Employee")],
                        default="EMPLOYEE",
                        max_length=16,
                    ),
                ),
                (
                    "square_team_member_id",
                    models.CharField(
                        blank=True,
                        help_text="The employee's Square team member ID. Required before their drawer shifts or inventory pushes can be attributed in Square.",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Unset instead of deleting: submissions must keep pointing at a real person.",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Access to the Django admin. Owners only.",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("pin_changed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ["display_name"],
                "indexes": [
                    models.Index(
                        fields=["square_team_member_id"],
                        name="accounts_us_square__457a60_idx",
                    ),
                    models.Index(
                        fields=["role", "is_active"], name="accounts_us_role_2b136f_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("role", "OWNER"), ("is_staff", False), _connector="OR"
                        ),
                        name="employee_is_not_staff",
                    )
                ],
            },
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
    ]
