# Generated by Django 6.1.1 on 2026-09-26 20:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("capture", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyReconciliation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INCOMPLETE", "Missing evidence"),
                            ("PROVISIONAL", "Waiting for Square"),
                            ("MISMATCH", "Needs review"),
                            ("MATCHED", "Matched"),
                            ("APPROVED", "Owner approved"),
                        ],
                        db_index=True,
                        default="INCOMPLETE",
                        max_length=20,
                    ),
                ),
                ("paper_values", models.JSONField(blank=True, default=dict)),
                ("square_values", models.JSONField(blank=True, default=dict)),
                ("check_results", models.JSONField(blank=True, default=list)),
                ("missing_evidence", models.JSONField(blank=True, default=list)),
                ("counted_cash_cents", models.BigIntegerField(blank=True, null=True)),
                (
                    "paper_expected_cash_cents",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "square_expected_cash_cents",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("lottery_sales_cents", models.BigIntegerField(blank=True, null=True)),
                (
                    "lottery_payouts_cents",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("explained_cash_cents", models.BigIntegerField(blank=True, null=True)),
                (
                    "unexplained_variance_cents",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("drawer_float_cents", models.BigIntegerField(blank=True, null=True)),
                (
                    "expected_collection_cents",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "owner_collected_cents",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "collection_variance_cents",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("collection_note", models.CharField(blank=True, max_length=300)),
                (
                    "collection_evidence_hash",
                    models.CharField(blank=True, max_length=64),
                ),
                ("collection_recorded_at", models.DateTimeField(blank=True, null=True)),
                ("square_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collection_recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_reconciliation",
                        to="capture.submission",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PayoutRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount_cents", models.BigIntegerField(blank=True, null=True)),
                (
                    "employee_reported_amount_cents",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "extracted_amount_cents",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("amount_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("game_name", models.CharField(blank=True, max_length=120)),
                (
                    "ticket_reference",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                (
                    "validation_reference",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Awaiting owner reimbursement"),
                            ("REIMBURSED", "Reimbursed"),
                            ("VOID", "Void"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("square_event_id", models.CharField(blank=True, max_length=64)),
                ("reimbursement_note", models.CharField(blank=True, max_length=300)),
                ("reimbursed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmed_payout_amounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reimbursed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reimbursed_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payout_record",
                        to="capture.submission",
                    ),
                ),
            ],
            options={
                "ordering": ["status", "-created_at"],
            },
        ),
    ]
