# Generated by Django 6.1.1 on 2026-09-26 20:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reconcile", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashPouchCount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("drawer_float_cents", models.BigIntegerField()),
                ("expected_cents", models.BigIntegerField()),
                ("counted_cents", models.BigIntegerField()),
                ("variance_cents", models.BigIntegerField()),
                ("evidence_hash", models.CharField(max_length=64)),
                ("note", models.CharField(blank=True, max_length=300)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "correction_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrections",
                        to="reconcile.cashpouchcount",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_pouch_counts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reconciliation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pouch_counts",
                        to="reconcile.dailyreconciliation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["reconciliation", "-created_at"],
                        name="reconcile_c_reconci_944394_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("drawer_float_cents__gte", 0)),
                        name="cash_pouch_float_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("counted_cents__gte", 0)),
                        name="cash_pouch_count_nonnegative",
                    ),
                ],
            },
        ),
    ]
