# Generated by Django 6.1.1 on 2026-09-26 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reconcile", "0003_backfill_cash_pouch_counts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CashPouchCount",
            new_name="DailyCashCount",
        ),
        migrations.RenameIndex(
            model_name="dailycashcount",
            old_name="reconcile_c_reconci_944394_idx",
            new_name="reconcile_d_reconci_304858_idx",
        ),
        migrations.RemoveConstraint(
            model_name="dailycashcount",
            name="cash_pouch_float_nonnegative",
        ),
        migrations.RemoveConstraint(
            model_name="dailycashcount",
            name="cash_pouch_count_nonnegative",
        ),
        migrations.AlterField(
            model_name="dailycashcount",
            name="entered_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="daily_cash_counts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dailycashcount",
            name="reconciliation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="daily_cash_counts",
                to="reconcile.dailyreconciliation",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailycashcount",
            constraint=models.CheckConstraint(
                condition=models.Q(("drawer_float_cents__gte", 0)),
                name="daily_cash_float_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailycashcount",
            constraint=models.CheckConstraint(
                condition=models.Q(("counted_cents__gte", 0)),
                name="daily_cash_count_nonnegative",
            ),
        ),
    ]
