# Generated by Django 6.1.1 on 2026-09-26 18:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DrawerFloat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_cents",
                    models.BigIntegerField(
                        help_text="The starting bank, in cents. 26500 is $265.00."
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        help_text="The first business day this float applies to."
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "set_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drawer_floats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-effective_from"],
                        name="core_drawer_effecti_f63e45_idx",
                    )
                ],
            },
        ),
    ]
