# Generated by Django 6.1.1 on 2026-09-26 20:17

import apps.capture.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("DAILY_REPORT", "Daily report"),
                            ("PAYOUT", "Lottery payout"),
                            ("INVENTORY", "Inventory delivery"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("QUEUED", "Queued"),
                            ("PROCESSING", "Reading photos"),
                            ("NEEDS_REVIEW", "Needs review"),
                            ("READY", "Ready for owner"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("FAILED", "Processing failed"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=24,
                    ),
                ),
                (
                    "business_day",
                    models.DateField(
                        db_index=True, default=apps.capture.models.current_business_day
                    ),
                ),
                ("employee_note", models.TextField(blank=True)),
                ("owner_note", models.TextField(blank=True)),
                ("processing_error", models.TextField(blank=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-business_day", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500,
                        upload_to=apps.capture.models.document_upload_path,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("media_type", models.CharField(max_length=100)),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                (
                    "requested_type",
                    models.CharField(
                        choices=[
                            ("AUTO", "Detect automatically"),
                            ("SQUARE_SALES_REPORT", "Square sales report"),
                            ("SQUARE_DRAWER_SCREEN", "Square drawer screen"),
                            ("LOTTERY_DAILY_SALES", "Lottery daily sales"),
                            ("LOTTERY_TICKET_BALANCE", "Lottery ticket balance"),
                            ("LOTTERY_DRAW_SCHEDULE", "Lottery draw schedule"),
                            ("LOTTERY_PAYOUT", "Lottery payout evidence"),
                            ("DELIVERY_INVOICE", "Delivery invoice"),
                            ("UNKNOWN", "Unknown document"),
                        ],
                        default="AUTO",
                        max_length=40,
                    ),
                ),
                (
                    "detected_type",
                    models.CharField(
                        choices=[
                            ("AUTO", "Detect automatically"),
                            ("SQUARE_SALES_REPORT", "Square sales report"),
                            ("SQUARE_DRAWER_SCREEN", "Square drawer screen"),
                            ("LOTTERY_DAILY_SALES", "Lottery daily sales"),
                            ("LOTTERY_TICKET_BALANCE", "Lottery ticket balance"),
                            ("LOTTERY_DRAW_SCHEDULE", "Lottery draw schedule"),
                            ("LOTTERY_PAYOUT", "Lottery payout evidence"),
                            ("DELIVERY_INVOICE", "Delivery invoice"),
                            ("UNKNOWN", "Unknown document"),
                        ],
                        default="AUTO",
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("PROCESSING", "Processing"),
                            ("EXTRACTED", "Extracted"),
                            ("REVIEWED", "Human reviewed"),
                            ("NEEDS_REVIEW", "Needs review"),
                            ("REJECTED", "Retake required"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="UPLOADED",
                        max_length=24,
                    ),
                ),
                ("extracted_data", models.JSONField(blank=True, default=dict)),
                ("check_results", models.JSONField(blank=True, default=list)),
                ("preparation_steps", models.JSONField(blank=True, default=list)),
                ("document_count", models.PositiveSmallIntegerField(default=1)),
                ("processing_error", models.TextField(blank=True)),
                ("provider", models.CharField(blank=True, max_length=30)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="capture.submission",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["kind", "status", "business_day"],
                name="capture_sub_kind_f53be2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["submitted_by", "-created_at"],
                name="capture_sub_submitt_57985b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["submission", "status"], name="capture_doc_submiss_7c63d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["detected_type"], name="capture_doc_detecte_169659_idx"
            ),
        ),
    ]
