# Generated by Django 6.1.1 on 2026-09-26 22:40

import uuid

import apps.capture.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("capture", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "submission_kind",
                    models.CharField(
                        choices=[
                            ("DAILY_REPORT", "Daily report"),
                            ("PAYOUT", "Lottery payout"),
                            ("INVENTORY", "Inventory delivery"),
                        ],
                        max_length=24,
                    ),
                ),
                ("field_name", models.CharField(max_length=40)),
                (
                    "file",
                    models.FileField(
                        max_length=500,
                        upload_to=apps.capture.models.pending_upload_path,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("media_type", models.CharField(max_length=100)),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True,
                        default=apps.capture.models.pending_upload_expiry,
                    ),
                ),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consumed_document",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staged_upload",
                        to="capture.document",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["uploaded_by", "consumed_at", "expires_at"],
                        name="capture_pen_uploade_1d5b76_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("consumed_at__isnull", True),
                                ("consumed_document__isnull", True),
                            ),
                            models.Q(
                                ("consumed_at__isnull", False),
                                ("consumed_document__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="capture_pending_consumption_consistent",
                    )
                ],
            },
        ),
    ]
