# Generated by Django 6.1.1 on 2026-09-26 20:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("capture", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, unique=True)),
                ("square_vendor_id", models.CharField(blank=True, max_length=64)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vendor_name_raw", models.CharField(blank=True, max_length=160)),
                ("invoice_number", models.CharField(blank=True, max_length=100)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("invoice_total_cents", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EXTRACTING", "Extracting"),
                            ("NEEDS_REVIEW", "Needs review"),
                            ("READY", "Ready to post"),
                            ("PUSHING", "Posting to Square"),
                            ("PUSHED", "Posted to Square"),
                            ("PUSHED_WITH_DRIFT", "Posted; count needs review"),
                            ("PUSHED_UNVERIFIED", "Posted; verification unavailable"),
                            ("FAILED", "Post failed"),
                        ],
                        db_index=True,
                        default="EXTRACTING",
                        max_length=24,
                    ),
                ),
                ("spreadsheet_revision", models.PositiveIntegerField(default=1)),
                ("square_batch_keys", models.JSONField(blank=True, default=list)),
                ("square_result", models.JSONField(blank=True, default=dict)),
                ("pushed_at", models.DateTimeField(blank=True, null=True)),
                ("push_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pushed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_pushes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery",
                        to="capture.submission",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="inventory.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SquareCatalogVariation",
            fields=[
                (
                    "variation_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("item_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("item_name", models.CharField(blank=True, max_length=300)),
                ("variation_name", models.CharField(blank=True, max_length=300)),
                ("sku", models.CharField(blank=True, db_index=True, max_length=100)),
                ("upc", models.CharField(blank=True, db_index=True, max_length=14)),
                ("gtin", models.CharField(blank=True, db_index=True, max_length=14)),
                ("track_inventory", models.BooleanField(default=False)),
                (
                    "present_at_location",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "location_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "ordering": ["item_name", "variation_name", "variation_id"],
                "indexes": [
                    models.Index(
                        fields=["sku", "present_at_location"],
                        name="inventory_s_sku_03c5d0_idx",
                    ),
                    models.Index(
                        fields=["upc", "present_at_location"],
                        name="inventory_s_upc_5b8d1f_idx",
                    ),
                    models.Index(
                        fields=["gtin", "present_at_location"],
                        name="inventory_s_gtin_4a38f7_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeliveryLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("vendor_sku", models.CharField(blank=True, max_length=100)),
                ("upc", models.CharField(blank=True, max_length=14)),
                ("description", models.CharField(max_length=300)),
                ("pack_text", models.CharField(blank=True, max_length=80)),
                (
                    "cases",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                ("units_per_case", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "received_units",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                ("unit_cost_cents", models.BigIntegerField(blank=True, null=True)),
                ("line_total_cents", models.BigIntegerField(blank=True, null=True)),
                (
                    "square_catalog_variation_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("square_item_name", models.CharField(blank=True, max_length=300)),
                (
                    "match_status",
                    models.CharField(
                        choices=[
                            ("UNMATCHED", "Unmatched"),
                            ("SUGGESTED", "Suggested match"),
                            ("MATCHED", "Matched"),
                            ("EXCLUDED", "Non-stock line"),
                        ],
                        default="UNMATCHED",
                        max_length=20,
                    ),
                ),
                ("included", models.BooleanField(default=True)),
                ("review_note", models.CharField(blank=True, max_length=300)),
                ("square_change_id", models.CharField(blank=True, max_length=64)),
                (
                    "square_count_before",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "square_count_variation_id",
                    models.CharField(blank=True, max_length=64),
                ),
                (
                    "projected_count_after",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "square_count_after",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "square_count_drift",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "square_count_snapshot_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "square_count_verified_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.delivery",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("delivery", "position"), name="delivery_line_position"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CatalogMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_sku", models.CharField(blank=True, max_length=100)),
                ("upc", models.CharField(blank=True, db_index=True, max_length=14)),
                ("description", models.CharField(max_length=300)),
                (
                    "square_catalog_variation_id",
                    models.CharField(db_index=True, max_length=64),
                ),
                ("square_item_name", models.CharField(blank=True, max_length=300)),
                (
                    "units_per_case",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "last_verified_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verified_catalog_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog_mappings",
                        to="inventory.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["description"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("vendor_sku", ""), _negated=True),
                        fields=("vendor", "vendor_sku"),
                        name="unique_vendor_sku_mapping",
                    )
                ],
            },
        ),
    ]
