# Generated by Django 6.1.1 on 2026-09-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryline",
            name="square_unit_cost_cents",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliveryline",
            name="square_unit_cost_currency",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name="deliveryline",
            name="square_unit_cost_source",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="squarecatalogvariation",
            name="default_unit_cost_cents",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="squarecatalogvariation",
            name="default_unit_cost_currency",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name="squarecatalogvariation",
            name="default_unit_cost_vendor_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="squarecatalogvariation",
            name="vendor_costs",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
