# Generated by Django 6.1.1 on 2026-09-26 21:28

import apps.inventory.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_square_cost_snapshots"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogCreationIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CLAIMED", "Protected request claimed"),
                            ("SUCCEEDED", "Created in Square"),
                            ("FAILED", "Request failed; safe retry required"),
                        ],
                        db_index=True,
                        default="CLAIMED",
                        max_length=16,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                ("payload_hash", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                ("normalized_sku", models.CharField(blank=True, max_length=100)),
                ("normalized_upc", models.CharField(blank=True, max_length=14)),
                ("square_item_id", models.CharField(blank=True, max_length=64)),
                ("square_variation_id", models.CharField(blank=True, max_length=64)),
                ("response", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="square_catalog_creation_intents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "line",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_creation_intent",
                        to="inventory.deliveryline",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("normalized_sku", ""), _negated=True),
                        fields=("normalized_sku",),
                        name="unique_square_create_sku",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("normalized_upc", ""), _negated=True),
                        fields=("normalized_upc",),
                        name="unique_square_create_upc",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InventorySandboxJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Preparing session"),
                            ("QUEUED", "Queued for sandbox"),
                            ("STAGED", "Invoice files staged"),
                            ("RUNNING", "Processing in sandbox"),
                            ("SUCCEEDED", "Output received"),
                            ("FAILED", "Processing failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "workflow_version",
                    models.CharField(default="inventory_invoice_v1", max_length=40),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("input_manifest", models.JSONField(blank=True, default=dict)),
                ("extracted_result", models.JSONField(blank=True, default=dict)),
                (
                    "output_workbook",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        upload_to=apps.inventory.models.inventory_sandbox_workbook_path,
                    ),
                ),
                ("output_sha256", models.CharField(blank=True, max_length=64)),
                (
                    "output_size_bytes",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("error_code", models.CharField(blank=True, max_length=60)),
                ("error_message", models.TextField(blank=True)),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("staged_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sandbox_jobs",
                        to="inventory.delivery",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_sandbox_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status__in", ["PENDING", "QUEUED", "STAGED", "RUNNING"])
                        ),
                        fields=("delivery",),
                        name="one_active_inventory_sandbox_job",
                    )
                ],
            },
        ),
    ]
