# Generated by Django 6.1.1 on 2026-10-03

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_sandbox_jobs_and_catalog_creation"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryline",
            name="loose_units",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=Decimal("0"),
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inventorysandboxjob",
            name="workflow_version",
            field=models.CharField(default="inventory_invoice_v2", max_length=40),
        ),
    ]
