# Generated by Django 6.1.1 on 2026-10-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_deliveryline_loose_units"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="printed_total_cases",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="printed_total_loose_units",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="printed_total_physical_units",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name="inventorysandboxjob",
            name="workflow_version",
            field=models.CharField(default="inventory_invoice_v3", max_length=40),
        ),
    ]
