# Generated by Django 6.1.1 on 2026-10-03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_squarecatalogvariation_pricing_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryPricingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_markup_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                    ),
                ),
                ("category_rules", models.JSONField(blank=True, default=dict)),
                ("product_overrides", models.JSONField(blank=True, default=dict)),
                ("category_assignments", models.JSONField(blank=True, default=dict)),
                ("preview_lines", models.JSONField(blank=True, default=list)),
                ("issues", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PREVIEWED", "Ready to update"),
                            ("PUSHING", "Updating Square"),
                            ("PUSHED", "Updated in Square"),
                            ("FAILED", "Update failed"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("frozen_payload", models.JSONField(blank=True, default=dict)),
                ("frozen_payload_hash", models.CharField(blank=True, max_length=64)),
                ("idempotency_key", models.CharField(blank=True, max_length=64)),
                ("square_result", models.JSONField(blank=True, default=dict)),
                ("square_error", models.TextField(blank=True)),
                ("prepared_at", models.DateTimeField(blank=True, null=True)),
                ("pushed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delivery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_plan",
                        to="inventory.delivery",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prepared_delivery_pricing_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pushed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pushed_delivery_pricing_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("idempotency_key", ""), _negated=True),
                        fields=("idempotency_key",),
                        name="unique_pricing_plan_idempotency_key",
                    ),
                ],
            },
        ),
    ]
